# Generated by Django 4.2.1 on 2023-05-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('K', 'Kaos/Kemeja'), ('J/S', 'Jaket/Sweater'), ('C', 'Celana')], max_length=4),
        ),
    ]
