# Generated by Django 4.2.1 on 2023-05-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('K', 'Kaos/Kemeja'), ('J/S', 'Jaket/Sweater'), ('C', 'Celana')], max_length=10)),
            ],
        ),
    ]
