# Generated by Django 4.2.1 on 2023-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nama_produk',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
