# Generated by Django 4.2.1 on 2023-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0012_alter_item_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
