# Generated by Django 4.2.1 on 2023-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0013_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kategori',
            field=models.CharField(default='C', max_length=100),
        ),
    ]
