# Generated by Django 4.2.1 on 2023-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0014_alter_item_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='nama_produk',
            field=models.CharField(max_length=100),
        ),
    ]
