# Generated by Django 4.2.1 on 2023-05-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0015_alter_item_kategori_alter_item_nama_produk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
