# Generated by Django 4.2.1 on 2023-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0016_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('kategori', models.SlugField(default='C', max_length=100)),
                ('nama_produk', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
