# Generated by Django 4.2.1 on 2023-05-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0017_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
